<?php
/*echo "COUCOUC";
die('ee');
echo $this->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('cms_homepage')
    ->toHtml();
*/?>

<div class="block" style="float: right;margin-bottom: 0.5%;margin-top: 0.5%;">
    <?php echo __('This is Custom Text'); ?>
</div>

<?php
/**
* Copyright © 2016 Magento. All rights reserved.
* See COPYING.txt for license details.
*/
?>
<p><?= 'Hello world!' ?></p>
