<h1>Affichage du tableau</h1>

<div id="contactslist">
    <h2>empty</h2>

    <table>
        <tr>
            <th>Name</th>
        </tr>

        <?php $contacts = $this->getData('contacts'); ?>

		<!-- Parcours du tableau vide -->
        <?php foreach ($contacts as $contact): ?>
            <tr>
                <td><?php echo $contact ?></td>
            </tr>
        <?php endforeach; ?>

        <tr>
            <td>there is no contact in this list</td>
        </tr>
    </table>



	<h2>10 éléments</h2>

    <table>
        <tr>
            <th>Name</th>
        </tr>

		<?php 
			// Appel de la méthode, du bloc
			$this->addContacts(10); 
		?>

        <?php $contacts = $this->getData('contacts'); ?>

		<!-- Parcours du tableau vide -->
        <?php foreach ($contacts as $contact): ?>
            <tr>
                <td><?php echo $contact ?></td>
            </tr>
        <?php endforeach; ?>
    </table>

	<h2>20 éléments</h2>

    <table>
        <tr>
            <th>Name</th>
        </tr>

		<?php 
			// Appel de la méthode, du bloc
			$this->addContacts(10); 
		?>

        <?php $contacts = $this->getData('contacts'); ?>

		<!-- Parcours du tableau vide -->
        <?php foreach ($contacts as $contact): ?>
            <tr>
                <td><?php echo $contact ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>